# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Amadeus(_OnPrem):
    _type = "amadeus"
    _icon_dir = "resources/onprem/amadeus"


class Api(_Amadeus):
    _icon = "API.png"


class Coorporations(_Amadeus):
    _icon = "Coorporations.png"


class Unicorn(_Amadeus):
    _icon = "Unicorn.png"


class Adds(_Amadeus):
    _icon = "aDDS.png"


class AaDiamongRating(_Amadeus):
    _icon = "aa-diamong-rating.png"


class AccessControl(_Amadeus):
    _icon = "access-control.png"


class AdExchange(_Amadeus):
    _icon = "ad-exchange.png"


class AddToCalendar(_Amadeus):
    _icon = "add-to-calendar.png"


class Add(_Amadeus):
    _icon = "add.png"


class Adserver(_Amadeus):
    _icon = "adserver.png"


class AdvancedPlatforms(_Amadeus):
    _icon = "advanced-platforms.png"


class Advertiser(_Amadeus):
    _icon = "advertiser.png"


class Advertising(_Amadeus):
    _icon = "advertising.png"


class AffiliateNetwork(_Amadeus):
    _icon = "affiliate-network.png"


class Agency(_Amadeus):
    _icon = "agency.png"


class Agenda(_Amadeus):
    _icon = "agenda.png"


class AirConditioning(_Amadeus):
    _icon = "air-conditioning.png"


class Airlines(_Amadeus):
    _icon = "airlines.png"


class Airplane01(_Amadeus):
    _icon = "airplane-01.png"


class Airplane02(_Amadeus):
    _icon = "airplane-02.png"


class Airplane03(_Amadeus):
    _icon = "airplane-03.png"


class Airplane04(_Amadeus):
    _icon = "airplane-04.png"


class Airplane05(_Amadeus):
    _icon = "airplane-05.png"


class AirportExpressTrain(_Amadeus):
    _icon = "airport-express-train.png"


class AirportOperations(_Amadeus):
    _icon = "airport-operations.png"


class AirportTower(_Amadeus):
    _icon = "airport-tower.png"


class Airport(_Amadeus):
    _icon = "airport.png"


class Alarm(_Amadeus):
    _icon = "alarm.png"


class Algorithm(_Amadeus):
    _icon = "algorithm.png"


class AllIndustries(_Amadeus):
    _icon = "all-industries.png"


class AmadeusCareersIcon(_Amadeus):
    _icon = "amadeus-careers-icon.png"


class AmadeusCareers(_Amadeus):
    _icon = "amadeus-careers.png"


class AmadeusCommercialIcon(_Amadeus):
    _icon = "amadeus-commercial-icon.png"


class AmadeusCommercial(_Amadeus):
    _icon = "amadeus-commercial.png"


class AmadeusCorporate(_Amadeus):
    _icon = "amadeus-corporate.png"


class AmadeusDevelopersIcon(_Amadeus):
    _icon = "amadeus-developers-icon.png"


class AmadeusDevelopers(_Amadeus):
    _icon = "amadeus-developers.png"


class AmadeusWorkshop(_Amadeus):
    _icon = "amadeus-workshop.png"


class Amadeus(_Amadeus):
    _icon = "amadeus.png"


class AnnualGeneralMeeting(_Amadeus):
    _icon = "annual-general-meeting.png"


class Apis(_Amadeus):
    _icon = "apis.png"


class ApprovedIdea(_Amadeus):
    _icon = "approved-idea.png"


class Approved(_Amadeus):
    _icon = "approved.png"


class ArrowBack(_Amadeus):
    _icon = "arrow-back.png"


class ArrowDown(_Amadeus):
    _icon = "arrow-down.png"


class ArrowForward(_Amadeus):
    _icon = "arrow-forward.png"


class ArrowUp(_Amadeus):
    _icon = "arrow-up.png"


class Article(_Amadeus):
    _icon = "article.png"


class ArtificialNtelligence(_Amadeus):
    _icon = "artificial-ntelligence.png"


class AskQuestions(_Amadeus):
    _icon = "ask-questions.png"


class AttachFile(_Amadeus):
    _icon = "attach-file.png"


class Attachment(_Amadeus):
    _icon = "attachment.png"


class Audience(_Amadeus):
    _icon = "audience.png"


class Audio(_Amadeus):
    _icon = "audio.png"


class AutomaticTransmission(_Amadeus):
    _icon = "automatic-transmission.png"


class Award(_Amadeus):
    _icon = "award.png"


class Backpacker(_Amadeus):
    _icon = "backpacker.png"


class BadWeatherConditions(_Amadeus):
    _icon = "bad-weather-conditions.png"


class Bank(_Amadeus):
    _icon = "bank.png"


class Banner(_Amadeus):
    _icon = "banner.png"


class Bar(_Amadeus):
    _icon = "bar.png"


class Bay(_Amadeus):
    _icon = "bay.png"


class BestAvailableRate(_Amadeus):
    _icon = "best-available-rate.png"


class BestRateInCategory(_Amadeus):
    _icon = "best-rate-in-category.png"


class Bicycle02(_Amadeus):
    _icon = "bicycle-02.png"


class Bicycle(_Amadeus):
    _icon = "bicycle.png"


class BigBang(_Amadeus):
    _icon = "big-bang.png"


class BigData02(_Amadeus):
    _icon = "big-data-02.png"


class BigData(_Amadeus):
    _icon = "big-data.png"


class BinocularsSearch(_Amadeus):
    _icon = "binoculars-search.png"


class Blacklinsting(_Amadeus):
    _icon = "blacklinsting.png"


class Blind(_Amadeus):
    _icon = "blind.png"


class Blockchain(_Amadeus):
    _icon = "blockchain.png"


class BoardMeeting(_Amadeus):
    _icon = "board-meeting.png"


class BoatTransfers(_Amadeus):
    _icon = "boat-transfers.png"


class Bookability(_Amadeus):
    _icon = "bookability.png"


class BookingAnalytics(_Amadeus):
    _icon = "booking-analytics.png"


class BookingFileNavigationButton(_Amadeus):
    _icon = "booking-file-navigation-button.png"


class BookingFile(_Amadeus):
    _icon = "booking-file.png"


class Books(_Amadeus):
    _icon = "books.png"


class Box01(_Amadeus):
    _icon = "box-01.png"


class Box02(_Amadeus):
    _icon = "box-02.png"


class Breakfast(_Amadeus):
    _icon = "breakfast.png"


class Building(_Amadeus):
    _icon = "building.png"


class BullEye(_Amadeus):
    _icon = "bull-eye.png"


class Bus01(_Amadeus):
    _icon = "bus-01.png"


class Bus02(_Amadeus):
    _icon = "bus-02.png"


class Bus03(_Amadeus):
    _icon = "bus-03.png"


class BusinessCentre(_Amadeus):
    _icon = "business-centre.png"


class BusinessOperations(_Amadeus):
    _icon = "business-operations.png"


class BusinessRole(_Amadeus):
    _icon = "business-role.png"


class BusinessTravelAgencies02(_Amadeus):
    _icon = "business-travel-agencies-02.png"


class BusinessTravelAgencies(_Amadeus):
    _icon = "business-travel-agencies.png"


class BussinessCentre01(_Amadeus):
    _icon = "bussiness-centre-01.png"


class Calendar(_Amadeus):
    _icon = "calendar.png"


class Camera(_Amadeus):
    _icon = "camera.png"


class CancelledFlight(_Amadeus):
    _icon = "cancelled-flight.png"


class Car01(_Amadeus):
    _icon = "car-01.png"


class Car02(_Amadeus):
    _icon = "car-02.png"


class Car03(_Amadeus):
    _icon = "car-03.png"


class CarCompanies(_Amadeus):
    _icon = "car-companies.png"


class CarDriver(_Amadeus):
    _icon = "car-driver.png"


class Cash(_Amadeus):
    _icon = "cash.png"


class Challenge02(_Amadeus):
    _icon = "challenge-02.png"


class Challenge(_Amadeus):
    _icon = "challenge.png"


class Change(_Amadeus):
    _icon = "change.png"


class Chart(_Amadeus):
    _icon = "chart.png"


class Chat(_Amadeus):
    _icon = "chat.png"


class CheckList(_Amadeus):
    _icon = "check-list.png"


class Check(_Amadeus):
    _icon = "check.png"


class Checklist(_Amadeus):
    _icon = "checklist.png"


class ChessPiece(_Amadeus):
    _icon = "chess-piece.png"


class ChildSeat(_Amadeus):
    _icon = "child-seat.png"


class Child(_Amadeus):
    _icon = "child.png"


class City(_Amadeus):
    _icon = "city.png"


class ClassifyInformation(_Amadeus):
    _icon = "classify-information.png"


class ClickThroughRate(_Amadeus):
    _icon = "click-through-rate.png"


class Click(_Amadeus):
    _icon = "click.png"


class Clipboard(_Amadeus):
    _icon = "clipboard.png"


class Clock(_Amadeus):
    _icon = "clock.png"


class Close02(_Amadeus):
    _icon = "close-02.png"


class Close(_Amadeus):
    _icon = "close.png"


class Cloud02(_Amadeus):
    _icon = "cloud-02.png"


class Cloud(_Amadeus):
    _icon = "cloud.png"


class CnmvFilings(_Amadeus):
    _icon = "cnmv-filings.png"


class Co2(_Amadeus):
    _icon = "co2.png"


class Coach(_Amadeus):
    _icon = "coach.png"


class Code(_Amadeus):
    _icon = "code.png"


class Coffee01(_Amadeus):
    _icon = "coffee-01.png"


class Coffee02(_Amadeus):
    _icon = "coffee-02.png"


class CommandPage01(_Amadeus):
    _icon = "command-page-01.png"


class CommandPage02(_Amadeus):
    _icon = "command-page-02.png"


class CommunitySupport(_Amadeus):
    _icon = "community-support.png"


class Company(_Amadeus):
    _icon = "company.png"


class ConfidentialMode(_Amadeus):
    _icon = "confidential-mode.png"


class Connected02(_Amadeus):
    _icon = "connected-02.png"


class ConnectedPerson(_Amadeus):
    _icon = "connected-person.png"


class ConnectedTravel(_Amadeus):
    _icon = "connected-travel.png"


class Connected(_Amadeus):
    _icon = "connected.png"


class Content02(_Amadeus):
    _icon = "content-02.png"


class ContentManagement(_Amadeus):
    _icon = "content-management.png"


class Content(_Amadeus):
    _icon = "content.png"


class ContractOrdering(_Amadeus):
    _icon = "contract-ordering.png"


class Control(_Amadeus):
    _icon = "control.png"


class ConversionAttribution(_Amadeus):
    _icon = "conversion-attribution.png"


class ConversionRate(_Amadeus):
    _icon = "conversion-rate.png"


class Conversion(_Amadeus):
    _icon = "conversion.png"


class CopyLink(_Amadeus):
    _icon = "copy-link.png"


class Copy(_Amadeus):
    _icon = "copy.png"


class CorporateGovernance(_Amadeus):
    _icon = "corporate-governance.png"


class Corporate(_Amadeus):
    _icon = "corporate.png"


class Corporations(_Amadeus):
    _icon = "corporations.png"


class CostDown(_Amadeus):
    _icon = "cost-down.png"


class Counter(_Amadeus):
    _icon = "counter.png"


class Creativity(_Amadeus):
    _icon = "creativity.png"


class CrossDevice(_Amadeus):
    _icon = "cross-device.png"


class CrossReference(_Amadeus):
    _icon = "cross-reference.png"


class Cruise02(_Amadeus):
    _icon = "cruise-02.png"


class Cruise(_Amadeus):
    _icon = "cruise.png"


class CsvFile(_Amadeus):
    _icon = "csv-file.png"


class Culture(_Amadeus):
    _icon = "culture.png"


class Cupcake(_Amadeus):
    _icon = "cupcake.png"


class Currency(_Amadeus):
    _icon = "currency.png"


class CustomerCentric(_Amadeus):
    _icon = "customer-centric.png"


class CustomerExperience(_Amadeus):
    _icon = "customer-experience.png"


class CustomerSatisfaction01(_Amadeus):
    _icon = "customer-satisfaction-01.png"


class CustomerSatisfaction02(_Amadeus):
    _icon = "customer-satisfaction-02.png"


class Customization(_Amadeus):
    _icon = "customization.png"


class CyberFingerprint(_Amadeus):
    _icon = "cyber-fingerprint.png"


class CyberSearch(_Amadeus):
    _icon = "cyber-search.png"


class CyberSecurity(_Amadeus):
    _icon = "cyber-security.png"


class Cycle(_Amadeus):
    _icon = "cycle.png"


class Data01(_Amadeus):
    _icon = "data-01.png"


class Data02(_Amadeus):
    _icon = "data-02.png"


class DataCentreErding(_Amadeus):
    _icon = "data-centre-erding.png"


class DataDrivenAdvertising(_Amadeus):
    _icon = "data-driven-advertising.png"


class DataMarketPlatform(_Amadeus):
    _icon = "data-market-platform.png"


class DataPartnership(_Amadeus):
    _icon = "data-partnership.png"


class Database(_Amadeus):
    _icon = "database.png"


class Deaf(_Amadeus):
    _icon = "deaf.png"


class DebtAndRating(_Amadeus):
    _icon = "debt-and-rating.png"


class Delete(_Amadeus):
    _icon = "delete.png"


class DemandGeneration(_Amadeus):
    _icon = "demand-generation.png"


class DemandSidePlatform(_Amadeus):
    _icon = "demand-side-platform.png"


class DepartureControl(_Amadeus):
    _icon = "departure-control.png"


class DesktopPc(_Amadeus):
    _icon = "desktop-pc.png"


class DestinationMarketingOrganization(_Amadeus):
    _icon = "destination-marketing-organization.png"


class Developer01(_Amadeus):
    _icon = "developer-01.png"


class Developer02(_Amadeus):
    _icon = "developer-02.png"


class DevelopersGroup01(_Amadeus):
    _icon = "developers-group-01.png"


class DevelopersGroup02(_Amadeus):
    _icon = "developers-group-02.png"


class DigitalFootprint(_Amadeus):
    _icon = "digital-footprint.png"


class Directions(_Amadeus):
    _icon = "directions.png"


class Disability(_Amadeus):
    _icon = "disability.png"


class Disaster(_Amadeus):
    _icon = "disaster.png"


class Diversity(_Amadeus):
    _icon = "diversity.png"


class Dmos(_Amadeus):
    _icon = "dmos.png"


class Done(_Amadeus):
    _icon = "done.png"


class DoorOpen(_Amadeus):
    _icon = "door-open.png"


class Download02(_Amadeus):
    _icon = "download-02.png"


class Download(_Amadeus):
    _icon = "download.png"


class DragHandle(_Amadeus):
    _icon = "drag-handle.png"


class Driver(_Amadeus):
    _icon = "driver.png"


class Dynamic(_Amadeus):
    _icon = "dynamic.png"


class Edit(_Amadeus):
    _icon = "edit.png"


class Efficiency(_Amadeus):
    _icon = "efficiency.png"


class Elder(_Amadeus):
    _icon = "elder.png"


class Email02(_Amadeus):
    _icon = "email-02.png"


class Email(_Amadeus):
    _icon = "email.png"


class Emergency(_Amadeus):
    _icon = "emergency.png"


class EngagementSurvey(_Amadeus):
    _icon = "engagement-survey.png"


class Engagement(_Amadeus):
    _icon = "engagement.png"


class Entertainment(_Amadeus):
    _icon = "entertainment.png"


class Environment(_Amadeus):
    _icon = "environment.png"


class EquityPlans(_Amadeus):
    _icon = "equity-plans.png"


class Erlenmeyer(_Amadeus):
    _icon = "erlenmeyer.png"


class ErrorPopUp(_Amadeus):
    _icon = "error-pop-up.png"


class Error(_Amadeus):
    _icon = "error.png"


class EstateCar(_Amadeus):
    _icon = "estate-car.png"


class EventPlanning(_Amadeus):
    _icon = "event-planning.png"


class Events(_Amadeus):
    _icon = "events.png"


class ExactMatch(_Amadeus):
    _icon = "exact-match.png"


class ExchangeTicket(_Amadeus):
    _icon = "exchange-ticket.png"


class ExcludedOfPolicy(_Amadeus):
    _icon = "excluded-of-policy.png"


class Exclusivity(_Amadeus):
    _icon = "exclusivity.png"


class ExpandCollapse01(_Amadeus):
    _icon = "expand-collapse-01.png"


class ExpandCollapse02(_Amadeus):
    _icon = "expand-collapse-02.png"


class Explore(_Amadeus):
    _icon = "explore.png"


class ExternalLink(_Amadeus):
    _icon = "external-link.png"


class ExtraBag(_Amadeus):
    _icon = "extra-bag.png"


class Facebook02(_Amadeus):
    _icon = "facebook-02.png"


class Facebook(_Amadeus):
    _icon = "facebook.png"


class Factory(_Amadeus):
    _icon = "factory.png"


class Family(_Amadeus):
    _icon = "family.png"


class FastBaggageCheckIn(_Amadeus):
    _icon = "fast-baggage-check-in.png"


class FastTrack(_Amadeus):
    _icon = "fast-track.png"


class Feedback(_Amadeus):
    _icon = "feedback.png"


class FemaSafetyCompliance(_Amadeus):
    _icon = "fema-safety-compliance.png"


class Ferry(_Amadeus):
    _icon = "ferry.png"


class FileProperties(_Amadeus):
    _icon = "file-properties.png"


class File(_Amadeus):
    _icon = "file.png"


class FiletypeAudio(_Amadeus):
    _icon = "filetype-audio.png"


class FiletypeDocument(_Amadeus):
    _icon = "filetype-document.png"


class FiletypeExcel(_Amadeus):
    _icon = "filetype-excel.png"


class FiletypeGraph(_Amadeus):
    _icon = "filetype-graph.png"


class FiletypeInfographic(_Amadeus):
    _icon = "filetype-infographic.png"


class FiletypeOther(_Amadeus):
    _icon = "filetype-other.png"


class FiletypePdf(_Amadeus):
    _icon = "filetype-pdf.png"


class FiletypePhoto(_Amadeus):
    _icon = "filetype-photo.png"


class FiletypeVideo(_Amadeus):
    _icon = "filetype-video.png"


class Filter(_Amadeus):
    _icon = "filter.png"


class Finance(_Amadeus):
    _icon = "finance.png"


class FinancialCalendar(_Amadeus):
    _icon = "financial-calendar.png"


class FinancialInformation(_Amadeus):
    _icon = "financial-information.png"


class FinancialReport(_Amadeus):
    _icon = "financial-report.png"


class Findability(_Amadeus):
    _icon = "findability.png"


class Fingerprint(_Amadeus):
    _icon = "fingerprint.png"


class Flame(_Amadeus):
    _icon = "flame.png"


class FlightDelay(_Amadeus):
    _icon = "flight-delay.png"


class Food(_Amadeus):
    _icon = "food.png"


class FourWheelDrive(_Amadeus):
    _icon = "four-wheel-drive.png"


class FullService(_Amadeus):
    _icon = "full-service.png"


class GasPump(_Amadeus):
    _icon = "gas-pump.png"


class Gateway(_Amadeus):
    _icon = "gateway.png"


class Gds(_Amadeus):
    _icon = "gds.png"


class Gears(_Amadeus):
    _icon = "gears.png"


class GenericStarRating(_Amadeus):
    _icon = "generic-star-rating.png"


class Glassdoor(_Amadeus):
    _icon = "glassdoor.png"


class GlobalImpact(_Amadeus):
    _icon = "global-impact.png"


class Globe01(_Amadeus):
    _icon = "globe-01.png"


class Globe02(_Amadeus):
    _icon = "globe-02.png"


class Gloves(_Amadeus):
    _icon = "gloves.png"


class GoToNext(_Amadeus):
    _icon = "go-to-next.png"


class GoogleAdwords(_Amadeus):
    _icon = "google-adwords.png"


class GooglePlus(_Amadeus):
    _icon = "google-plus.png"


class GooglePlus2(_Amadeus):
    _icon = "google-plus2.png"


class GreenEnergy(_Amadeus):
    _icon = "green-energy.png"


class GroundHandlersGroundOperations(_Amadeus):
    _icon = "ground-handlers-ground-operations.png"


class GroundHandlers(_Amadeus):
    _icon = "ground-handlers.png"


class GroundTransportation(_Amadeus):
    _icon = "ground-transportation.png"


class Group(_Amadeus):
    _icon = "group.png"


class HealthClub(_Amadeus):
    _icon = "health-club.png"


class Heart(_Amadeus):
    _icon = "heart.png"


class Helicopter(_Amadeus):
    _icon = "helicopter.png"


class Home(_Amadeus):
    _icon = "home.png"


class Hospitality(_Amadeus):
    _icon = "hospitality.png"


class Hotel01(_Amadeus):
    _icon = "hotel-01.png"


class Hotel02(_Amadeus):
    _icon = "hotel-02.png"


class Hotel03(_Amadeus):
    _icon = "hotel-03.png"


class Hotel04(_Amadeus):
    _icon = "hotel-04.png"


class Hotels(_Amadeus):
    _icon = "hotels.png"


class House(_Amadeus):
    _icon = "house.png"


class IdeaExpertise(_Amadeus):
    _icon = "idea-expertise.png"


class InPolicyOutOfPolicy(_Amadeus):
    _icon = "in-policy-out-of-policy.png"


class IndustryRelations(_Amadeus):
    _icon = "industry-relations.png"


class IndustryUpdates(_Amadeus):
    _icon = "industry-updates.png"


class Infant(_Amadeus):
    _icon = "infant.png"


class Information(_Amadeus):
    _icon = "information.png"


class Innovation02(_Amadeus):
    _icon = "innovation-02.png"


class Innovation(_Amadeus):
    _icon = "innovation.png"


class Insights(_Amadeus):
    _icon = "insights.png"


class Instagram(_Amadeus):
    _icon = "instagram.png"


class Insurance(_Amadeus):
    _icon = "insurance.png"


class Interface01(_Amadeus):
    _icon = "interface-01.png"


class Interface02(_Amadeus):
    _icon = "interface-02.png"


class Internet(_Amadeus):
    _icon = "internet.png"


class InvestorRelations(_Amadeus):
    _icon = "investor-relations.png"


class ItSolutions(_Amadeus):
    _icon = "it-solutions.png"


class KeyboardArrowDown(_Amadeus):
    _icon = "keyboard-arrow-down.png"


class KeyboardArrowLeft(_Amadeus):
    _icon = "keyboard-arrow-left.png"


class KeyboardArrowRight(_Amadeus):
    _icon = "keyboard-arrow-right.png"


class KeyboardArrowUp(_Amadeus):
    _icon = "keyboard-arrow-up.png"


class Keyboard(_Amadeus):
    _icon = "keyboard.png"


class Keys(_Amadeus):
    _icon = "keys.png"


class KnowledgeSharing(_Amadeus):
    _icon = "knowledge-sharing.png"


class Knowledge(_Amadeus):
    _icon = "knowledge.png"


class Language(_Amadeus):
    _icon = "language.png"


class LastMinute(_Amadeus):
    _icon = "last-minute.png"


class LaundryService(_Amadeus):
    _icon = "laundry-service.png"


class Laurel(_Amadeus):
    _icon = "laurel.png"


class Lavatory(_Amadeus):
    _icon = "lavatory.png"


class Learning(_Amadeus):
    _icon = "learning.png"


class Leaves(_Amadeus):
    _icon = "leaves.png"


class LegendOfMapMarker(_Amadeus):
    _icon = "legend-of-map-marker.png"


class Leisure01(_Amadeus):
    _icon = "leisure-01.png"


class Leisure02(_Amadeus):
    _icon = "leisure-02.png"


class Lift(_Amadeus):
    _icon = "lift.png"


class LightBulb(_Amadeus):
    _icon = "light-bulb.png"


class Like(_Amadeus):
    _icon = "like.png"


class Limo(_Amadeus):
    _icon = "limo.png"


class Linkedin02(_Amadeus):
    _icon = "linkedin-02.png"


class Linkedin(_Amadeus):
    _icon = "linkedin.png"


class LiveTravelSpace(_Amadeus):
    _icon = "live-travel-space.png"


class LocationPin(_Amadeus):
    _icon = "location-pin.png"


class Location(_Amadeus):
    _icon = "location.png"


class LostLuggage(_Amadeus):
    _icon = "lost-luggage.png"


class LoungeAccess(_Amadeus):
    _icon = "lounge-access.png"


class Luggage01(_Amadeus):
    _icon = "luggage-01.png"


class Luggage02(_Amadeus):
    _icon = "luggage-02.png"


class MachineLearning(_Amadeus):
    _icon = "machine-learning.png"


class Man(_Amadeus):
    _icon = "man.png"


class Manager01(_Amadeus):
    _icon = "manager-01.png"


class Manager02(_Amadeus):
    _icon = "manager-02.png"


class ManualTransmission(_Amadeus):
    _icon = "manual-transmission.png"


class Map(_Amadeus):
    _icon = "map.png"


class MarketShare(_Amadeus):
    _icon = "market-share.png"


class Meal(_Amadeus):
    _icon = "meal.png"


class MediaConnected(_Amadeus):
    _icon = "media-connected.png"


class MedicalAssistance(_Amadeus):
    _icon = "medical-assistance.png"


class MeetingRoom(_Amadeus):
    _icon = "meeting-room.png"


class MeetingRooms(_Amadeus):
    _icon = "meeting-rooms.png"


class Megaphone(_Amadeus):
    _icon = "megaphone.png"


class Menu(_Amadeus):
    _icon = "menu.png"


class MetaSearch(_Amadeus):
    _icon = "meta-search.png"


class Metasearch(_Amadeus):
    _icon = "metasearch.png"


class MicroChip(_Amadeus):
    _icon = "micro-chip.png"


class MissedConnection(_Amadeus):
    _icon = "missed-connection.png"


class Mobile02(_Amadeus):
    _icon = "mobile-02.png"


class MobileAdvertising(_Amadeus):
    _icon = "mobile-advertising.png"


class Mobile(_Amadeus):
    _icon = "mobile.png"


class Mobility(_Amadeus):
    _icon = "mobility.png"


class Monetization(_Amadeus):
    _icon = "monetization.png"


class MoneyBag02(_Amadeus):
    _icon = "money-bag-02.png"


class MoneyBagWithCurrencyIndication(_Amadeus):
    _icon = "money-bag-with-currency-indication.png"


class MoneyBag(_Amadeus):
    _icon = "money-bag.png"


class MoreActions(_Amadeus):
    _icon = "more-actions.png"


class Morphing(_Amadeus):
    _icon = "morphing.png"


class Motocycle(_Amadeus):
    _icon = "motocycle.png"


class Mountains(_Amadeus):
    _icon = "mountains.png"


class Mouse(_Amadeus):
    _icon = "mouse.png"


class Music(_Amadeus):
    _icon = "music.png"


class MutualExchange(_Amadeus):
    _icon = "mutual-exchange.png"


class Nationalities(_Amadeus):
    _icon = "nationalities.png"


class NativeAdvertising(_Amadeus):
    _icon = "native-advertising.png"


class NavbarExpand(_Amadeus):
    _icon = "navbar-expand.png"


class Ndc(_Amadeus):
    _icon = "ndc.png"


class NegotiatedRatesAvailable(_Amadeus):
    _icon = "negotiated-rates-available.png"


class Network01(_Amadeus):
    _icon = "network-01.png"


class Network02(_Amadeus):
    _icon = "network-02.png"


class Network03(_Amadeus):
    _icon = "network-03.png"


class NewWindow(_Amadeus):
    _icon = "new-window.png"


class NoBreakfast(_Amadeus):
    _icon = "no-breakfast.png"


class NoPreview(_Amadeus):
    _icon = "no-preview.png"


class Notifications(_Amadeus):
    _icon = "notifications.png"


class NumberOfPassangers(_Amadeus):
    _icon = "number-of-passangers.png"


class Observatory(_Amadeus):
    _icon = "observatory.png"


class Offices(_Amadeus):
    _icon = "offices.png"


class Oil(_Amadeus):
    _icon = "oil.png"


class OnlineBooking(_Amadeus):
    _icon = "online-booking.png"


class OnlineConversion(_Amadeus):
    _icon = "online-conversion.png"


class OnlineTraining(_Amadeus):
    _icon = "online-training.png"


class OnlineTravelAgencies02(_Amadeus):
    _icon = "online-travel-agencies-02.png"


class OnlineTravelAgencies(_Amadeus):
    _icon = "online-travel-agencies.png"


class OpenSource(_Amadeus):
    _icon = "open-source.png"


class Open(_Amadeus):
    _icon = "open.png"


class Operations(_Amadeus):
    _icon = "operations.png"


class Optimization(_Amadeus):
    _icon = "optimization.png"


class OrganChart(_Amadeus):
    _icon = "organ-chart.png"


class OriginAndDestination(_Amadeus):
    _icon = "origin-and-destination.png"


class Paris(_Amadeus):
    _icon = "paris.png"


class Parking(_Amadeus):
    _icon = "parking.png"


class Passengers(_Amadeus):
    _icon = "passengers.png"


class Passport(_Amadeus):
    _icon = "passport.png"


class PaymentCompanies(_Amadeus):
    _icon = "payment-companies.png"


class Payment(_Amadeus):
    _icon = "payment.png"


class Payments(_Amadeus):
    _icon = "payments.png"


class PcHookupInRoom(_Amadeus):
    _icon = "pc-hookup-in-room.png"


class PcScreen(_Amadeus):
    _icon = "pc-screen.png"


class Pencil(_Amadeus):
    _icon = "pencil.png"


class People(_Amadeus):
    _icon = "people.png"


class PercentageTag(_Amadeus):
    _icon = "percentage-tag.png"


class PetsAccepted(_Amadeus):
    _icon = "pets-accepted.png"


class Phone02(_Amadeus):
    _icon = "phone-02.png"


class Phone(_Amadeus):
    _icon = "phone.png"


class Photo(_Amadeus):
    _icon = "photo.png"


class Picture(_Amadeus):
    _icon = "picture.png"


class Pictures(_Amadeus):
    _icon = "pictures.png"


class PiggyBank(_Amadeus):
    _icon = "piggy-bank.png"


class Pinterest(_Amadeus):
    _icon = "pinterest.png"


class PlayArrow(_Amadeus):
    _icon = "play-arrow.png"


class PlayCircle(_Amadeus):
    _icon = "play-circle.png"


class Plug(_Amadeus):
    _icon = "plug.png"


class Portal(_Amadeus):
    _icon = "portal.png"


class Prediction(_Amadeus):
    _icon = "prediction.png"


class Preferred(_Amadeus):
    _icon = "preferred.png"


class Present(_Amadeus):
    _icon = "present.png"


class Press(_Amadeus):
    _icon = "press.png"


class PriceBenchmark(_Amadeus):
    _icon = "price-benchmark.png"


class PriceTag01(_Amadeus):
    _icon = "price-tag-01.png"


class PriceTag02(_Amadeus):
    _icon = "price-tag-02.png"


class Print02(_Amadeus):
    _icon = "print-02.png"


class Print(_Amadeus):
    _icon = "print.png"


class Privacy(_Amadeus):
    _icon = "privacy.png"


class PrivateJet(_Amadeus):
    _icon = "private-jet.png"


class PrivateNetwork(_Amadeus):
    _icon = "private-network.png"


class Prize02(_Amadeus):
    _icon = "prize-02.png"


class Prize(_Amadeus):
    _icon = "prize.png"


class Process(_Amadeus):
    _icon = "process.png"


class Profile01(_Amadeus):
    _icon = "profile-01.png"


class Profile02(_Amadeus):
    _icon = "profile-02.png"


class Profile03(_Amadeus):
    _icon = "profile-03.png"


class Profile04(_Amadeus):
    _icon = "profile-04.png"


class ProfileWoman(_Amadeus):
    _icon = "profile-woman.png"


class ProgrammaticAdvertising(_Amadeus):
    _icon = "programmatic-advertising.png"


class Prototype(_Amadeus):
    _icon = "prototype.png"


class Publisher(_Amadeus):
    _icon = "publisher.png"


class PulseSurvey(_Amadeus):
    _icon = "pulse-survey.png"


class Purchase(_Amadeus):
    _icon = "purchase.png"


class Puzzle02(_Amadeus):
    _icon = "puzzle-02.png"


class Puzzle(_Amadeus):
    _icon = "puzzle.png"


class Q1Expectation(_Amadeus):
    _icon = "q1-expectation.png"


class Q10BestFriend(_Amadeus):
    _icon = "q10-best-friend.png"


class Q11Progress(_Amadeus):
    _icon = "q11-progress.png"


class Q12LearnAndGrow(_Amadeus):
    _icon = "q12-learn-and-grow.png"


class Q2MaterialAndEquipment(_Amadeus):
    _icon = "q2-material-and-equipment.png"


class Q3DoBest(_Amadeus):
    _icon = "q3-do-best.png"


class Q4Recognition(_Amadeus):
    _icon = "q4-recognition.png"


class Q5Development(_Amadeus):
    _icon = "q5-development.png"


class Q7OpinionsCount(_Amadeus):
    _icon = "q7-opinions-count.png"


class Q8MissionAndPurpose(_Amadeus):
    _icon = "q8-mission-and-purpose.png"


class QrCodes(_Amadeus):
    _icon = "qr-codes.png"


class Question(_Amadeus):
    _icon = "question.png"


class Rail(_Amadeus):
    _icon = "rail.png"


class Railways(_Amadeus):
    _icon = "railways.png"


class Ranking(_Amadeus):
    _icon = "ranking.png"


class RegulatoryBodies(_Amadeus):
    _icon = "regulatory-bodies.png"


class Relevance(_Amadeus):
    _icon = "relevance.png"


class RemoteWork(_Amadeus):
    _icon = "remote-work.png"


class Remove(_Amadeus):
    _icon = "remove.png"


class Reply(_Amadeus):
    _icon = "reply.png"


class Report(_Amadeus):
    _icon = "report.png"


class Reporting(_Amadeus):
    _icon = "reporting.png"


class Research02(_Amadeus):
    _icon = "research-02.png"


class Research(_Amadeus):
    _icon = "research.png"


class Reservation(_Amadeus):
    _icon = "reservation.png"


class Reset(_Amadeus):
    _icon = "reset.png"


class ResponseTime(_Amadeus):
    _icon = "response-time.png"


class Restaurant(_Amadeus):
    _icon = "restaurant.png"


class RetailTravelAgencies02(_Amadeus):
    _icon = "retail-travel-agencies-02.png"


class RetailTravelAgencies(_Amadeus):
    _icon = "retail-travel-agencies.png"


class RevenuesUp(_Amadeus):
    _icon = "revenues-up.png"


class Robot(_Amadeus):
    _icon = "robot.png"


class Rocket(_Amadeus):
    _icon = "rocket.png"


class Route(_Amadeus):
    _icon = "route.png"


class SadFace(_Amadeus):
    _icon = "sad-face.png"


class SafeDepBox(_Amadeus):
    _icon = "safe-dep-box.png"


class Sail(_Amadeus):
    _icon = "sail.png"


class SalesAndRevenue(_Amadeus):
    _icon = "sales-and-revenue.png"


class SalesMarketing(_Amadeus):
    _icon = "sales-marketing.png"


class SatNav(_Amadeus):
    _icon = "sat-nav.png"


class SatisfactionEmoticonsDissatisfied(_Amadeus):
    _icon = "satisfaction-emoticons-dissatisfied.png"


class SatisfactionEmoticonsSatisfied(_Amadeus):
    _icon = "satisfaction-emoticons-satisfied.png"


class SatisfactionEmoticonsSomewhatSatisfied(_Amadeus):
    _icon = "satisfaction-emoticons-somewhat-satisfied.png"


class SatisfactionEmoticonsVeryDissatisfied(_Amadeus):
    _icon = "satisfaction-emoticons-very-dissatisfied.png"


class SatisfactionEmoticonsVerySatisfied(_Amadeus):
    _icon = "satisfaction-emoticons-very-satisfied.png"


class SaveAndConfirm(_Amadeus):
    _icon = "save-and-confirm.png"


class ScheduleChange(_Amadeus):
    _icon = "schedule-change.png"


class Schedule(_Amadeus):
    _icon = "schedule.png"


class SearchFlight(_Amadeus):
    _icon = "search-flight.png"


class SearchTravel(_Amadeus):
    _icon = "search-travel.png"


class Search(_Amadeus):
    _icon = "search.png"


class Seat(_Amadeus):
    _icon = "seat.png"


class Security(_Amadeus):
    _icon = "security.png"


class SelectArrow(_Amadeus):
    _icon = "select-arrow.png"


class Select(_Amadeus):
    _icon = "select.png"


class Selfie(_Amadeus):
    _icon = "selfie.png"


class SendEmail(_Amadeus):
    _icon = "send-email.png"


class ServerAccept(_Amadeus):
    _icon = "server-accept.png"


class ServerCancel(_Amadeus):
    _icon = "server-cancel.png"


class ServerEmpty(_Amadeus):
    _icon = "server-empty.png"


class ServerRun(_Amadeus):
    _icon = "server-run.png"


class ServerSecurity(_Amadeus):
    _icon = "server-security.png"


class ServerStop(_Amadeus):
    _icon = "server-stop.png"


class Server(_Amadeus):
    _icon = "server.png"


class ServicesConsulting(_Amadeus):
    _icon = "services-consulting.png"


class Settings(_Amadeus):
    _icon = "settings.png"


class Share02(_Amadeus):
    _icon = "share-02.png"


class ShareInformation(_Amadeus):
    _icon = "share-information.png"


class Share(_Amadeus):
    _icon = "share.png"


class SharedTransfer(_Amadeus):
    _icon = "shared-transfer.png"


class Shopping(_Amadeus):
    _icon = "shopping.png"


class Sitemap(_Amadeus):
    _icon = "sitemap.png"


class Smiley(_Amadeus):
    _icon = "smiley.png"


class Snack(_Amadeus):
    _icon = "snack.png"


class SocialMedia01(_Amadeus):
    _icon = "social-media-01.png"


class SocialMedia(_Amadeus):
    _icon = "social-media.png"


class Sort(_Amadeus):
    _icon = "sort.png"


class Spa(_Amadeus):
    _icon = "spa.png"


class Speech(_Amadeus):
    _icon = "speech.png"


class Speed(_Amadeus):
    _icon = "speed.png"


class Speedometer(_Amadeus):
    _icon = "speedometer.png"


class SportsEquipment(_Amadeus):
    _icon = "sports-equipment.png"


class StaffBonus(_Amadeus):
    _icon = "staff-bonus.png"


class Staircase(_Amadeus):
    _icon = "staircase.png"


class StockHigh(_Amadeus):
    _icon = "stock-high.png"


class StockLow(_Amadeus):
    _icon = "stock-low.png"


class StockVolume(_Amadeus):
    _icon = "stock-volume.png"


class StopWatch(_Amadeus):
    _icon = "stop-watch.png"


class Strategy(_Amadeus):
    _icon = "strategy.png"


class Strike(_Amadeus):
    _icon = "strike.png"


class StudentGraduates(_Amadeus):
    _icon = "student-graduates.png"


class SupplySidePlatform(_Amadeus):
    _icon = "supply-side-platform.png"


class Support02(_Amadeus):
    _icon = "support-02.png"


class Support(_Amadeus):
    _icon = "support.png"


class Survey(_Amadeus):
    _icon = "survey.png"


class Sustainability(_Amadeus):
    _icon = "sustainability.png"


class SwimmingPool(_Amadeus):
    _icon = "swimming-pool.png"


class Tablet02(_Amadeus):
    _icon = "tablet-02.png"


class Tablet(_Amadeus):
    _icon = "tablet.png"


class Tap(_Amadeus):
    _icon = "tap.png"


class TargetGroup(_Amadeus):
    _icon = "target-group.png"


class Targeting(_Amadeus):
    _icon = "targeting.png"


class Taxi(_Amadeus):
    _icon = "taxi.png"


class TeamWork(_Amadeus):
    _icon = "team-work.png"


class Technology02(_Amadeus):
    _icon = "technology-02.png"


class TechnologyRole(_Amadeus):
    _icon = "technology-role.png"


class Technology(_Amadeus):
    _icon = "technology.png"


class Terminal(_Amadeus):
    _icon = "terminal.png"


class Thermometer(_Amadeus):
    _icon = "thermometer.png"


class Thief(_Amadeus):
    _icon = "thief.png"


class Thoughts(_Amadeus):
    _icon = "thoughts.png"


class Thumbnail(_Amadeus):
    _icon = "thumbnail.png"


class Ticket02(_Amadeus):
    _icon = "ticket-02.png"


class TicketImage01(_Amadeus):
    _icon = "ticket-image-01.png"


class TicketImage02(_Amadeus):
    _icon = "ticket-image-02.png"


class TicketImage03(_Amadeus):
    _icon = "ticket-image-03.png"


class Ticket(_Amadeus):
    _icon = "ticket.png"


class Time(_Amadeus):
    _icon = "time.png"


class TireChain(_Amadeus):
    _icon = "tire-chain.png"


class Toilets(_Amadeus):
    _icon = "toilets.png"


class Tools(_Amadeus):
    _icon = "tools.png"


class Torch(_Amadeus):
    _icon = "torch.png"


class TourOperators(_Amadeus):
    _icon = "tour-operators.png"


class Traba(_Amadeus):
    _icon = "traba.png"


class TradeFair(_Amadeus):
    _icon = "trade-fair.png"


class TrafficAquisition(_Amadeus):
    _icon = "traffic-aquisition.png"


class Transfer01(_Amadeus):
    _icon = "transfer-01.png"


class Transfer02(_Amadeus):
    _icon = "transfer-02.png"


class TransfersDriver(_Amadeus):
    _icon = "transfers-driver.png"


class Transportation(_Amadeus):
    _icon = "transportation.png"


class TravelAgency01(_Amadeus):
    _icon = "travel-agency-01.png"


class TravelAgency02(_Amadeus):
    _icon = "travel-agency-02.png"


class TravelAgency03(_Amadeus):
    _icon = "travel-agency-03.png"


class TravelAgentBusiness(_Amadeus):
    _icon = "travel-agent-business.png"


class TravelInsurance(_Amadeus):
    _icon = "travel-insurance.png"


class TravelIntelligence02(_Amadeus):
    _icon = "travel-intelligence-02.png"


class TravelIntelligence(_Amadeus):
    _icon = "travel-intelligence.png"


class TravelIntent(_Amadeus):
    _icon = "travel-intent.png"


class TravelSearchCompanies(_Amadeus):
    _icon = "travel-search-companies.png"


class Travelcast(_Amadeus):
    _icon = "travelcast.png"


class TravellerManagement(_Amadeus):
    _icon = "traveller-management.png"


class Traveller(_Amadeus):
    _icon = "traveller.png"


class Tree(_Amadeus):
    _icon = "tree.png"


class Tribe(_Amadeus):
    _icon = "tribe.png"


class Truck(_Amadeus):
    _icon = "truck.png"


class Tv(_Amadeus):
    _icon = "tv.png"


class TwitterOutline(_Amadeus):
    _icon = "twitter-outline.png"


class Twitter(_Amadeus):
    _icon = "twitter.png"


class TwoSeaterCar(_Amadeus):
    _icon = "two-seater-car.png"


class Umbrella(_Amadeus):
    _icon = "umbrella.png"


class UnaccompaniedMinor(_Amadeus):
    _icon = "unaccompanied-minor.png"


class Unicorn02(_Amadeus):
    _icon = "unicorn-02.png"


class University(_Amadeus):
    _icon = "university.png"


class Upgrade(_Amadeus):
    _icon = "upgrade.png"


class UsbKey(_Amadeus):
    _icon = "usb-key.png"


class UserQuestion(_Amadeus):
    _icon = "user-question.png"


class UserValidate01(_Amadeus):
    _icon = "user-validate-01.png"


class UserValidate02(_Amadeus):
    _icon = "user-validate-02.png"


class ValueTag01(_Amadeus):
    _icon = "value-tag-01.png"


class ValueTag02(_Amadeus):
    _icon = "value-tag-02.png"


class Ventures(_Amadeus):
    _icon = "ventures.png"


class VersionHistory(_Amadeus):
    _icon = "version-history.png"


class VerticalBar(_Amadeus):
    _icon = "vertical-bar.png"


class VideoAdvertising(_Amadeus):
    _icon = "video-advertising.png"


class Video(_Amadeus):
    _icon = "video.png"


class Vip(_Amadeus):
    _icon = "vip.png"


class Visa(_Amadeus):
    _icon = "visa.png"


class Warning(_Amadeus):
    _icon = "warning.png"


class Water(_Amadeus):
    _icon = "water.png"


class WeaponsControl(_Amadeus):
    _icon = "weapons-control.png"


class Weather(_Amadeus):
    _icon = "weather.png"


class Wellbeingprograms(_Amadeus):
    _icon = "wellbeingprograms.png"


class WifiAvailable(_Amadeus):
    _icon = "wifi-available.png"


class Wifi(_Amadeus):
    _icon = "wifi.png"


class Woman(_Amadeus):
    _icon = "woman.png"


class Workdesk(_Amadeus):
    _icon = "workdesk.png"


class Working(_Amadeus):
    _icon = "working.png"


class WorldTravel01(_Amadeus):
    _icon = "world-travel-01.png"


class WorldTravel02(_Amadeus):
    _icon = "world-travel-02.png"


class WorldwideConnection(_Amadeus):
    _icon = "worldwide-connection.png"


class Worldwide(_Amadeus):
    _icon = "worldwide.png"


class Write(_Amadeus):
    _icon = "write.png"


class WrittingSet(_Amadeus):
    _icon = "writting-set.png"


class XmlFeed(_Amadeus):
    _icon = "xml-feed.png"


class You(_Amadeus):
    _icon = "you.png"


class Youtube02(_Amadeus):
    _icon = "youtube-02.png"


class Youtube(_Amadeus):
    _icon = "youtube.png"


# Aliases
